### ISSUE TITLE
Can you update the http version of binance_pay?

### ISSUE THREAD

**Issue by SunLin1997** [MarsadMaqsood/binance_pay#1]
Because every version of binance_pay depends on http ^0.13.6 and smile_up depends on http ^1.1.0, binance_pay is forbidden.
So, because smile_up depends on binance_pay ^0.0.2, version solving failed.

Can you update the http version of binance_pay?

**Comment by MarsadMaqsood** [comment]
Update to the latest [version](https://pub.dev/packages/binance_pay) :)
